Updated German translation
Memmy-App/memmy pull request #833
Opened 2023-07-23 16:40 UTC by phriedrich

### PR Creator Checklist

Ensure you've checked the following before submitting your PR:

- [ ] You've discussed making your changes with a member of the dev team per contributing rules in the README
- [x] Your changes are free of any lint errors
- [x] Your changes are free of any typescript errors
- [x] You've tested your changes

### Summary

Updates and fixes for several strings in the German translation, also adding previously untranslated terms.

Apart from simple spelling mistakes, I have tried to fix grammatical errors. Where possible I have tried to use the same terms Lemmy's web interface is using to avoid confusion. 

For example, while the correct English plural for "community" is "communities", this doesn't apply when using the English word within a German text. The _recommendation_ ist to use the English singular form and add an _s_, resulting in "Communitys". Also note the capital first letter used in German for all nouns.

This may look a bit weird, but is the common form. Also the Lemmy team uses this in the translation for the web frontend, so we should try to keep it consistent.

### Screenshots

> If the UI has been changed, include screenshots. 
> We will not review your PR without screenshots if they are applicable.

### Test Plan

> Please documemnt the steps required to test your PR

2023-07-23 21:18 UTC, sgriff96 commented
@Felix-Staud can you take a look at this

2023-07-23 21:39 UTC, Felix-Staud commented
Thanks for fixing all my translation mess ups. 
I had some small feedbacks. Please let me know when it's ready for re-review

2023-07-24 05:15 UTC, phriedrich commented
@Felix-Staud Where can I see this feedback?

2023-07-24 05:25 UTC, Felix-Staud commented
> @Felix-Staud Where can I see this feedback?

Inside the “files” tab you can see the exact lines I’ve commented

2023-07-24 05:25 UTC, Felix-Staud requested changes

2023-07-24 05:37 UTC, phriedrich commented on src/plugins/i18n/locales/de.json
> +    "blocked": "Blockiert {{0}}",
Ah, I see. I'll make some fixes and will update.

2023-07-24 05:37 UTC, phriedrich commented on src/plugins/i18n/locales/de.json
> +        "header": "Einstellungen für als gelesen Markieren",
"Als gelesen Markieren" should do, when this is followed by the list, it should be clear enough.

2023-07-24 05:41 UTC, phriedrich commented on src/plugins/i18n/locales/de.json
> +  "Post": "Beitrag erstellen",
![Bildschirmfoto 2023-07-24 um 07 40 42](https://github.com/Memmy-App/memmy/assets/470153/e07f16fb-7bd5-4dd1-94be-d4bf1bdffb6e)

Together with the + in front this should be clear enough.

2023-07-24 05:45 UTC, phriedrich commented on src/plugins/i18n/locales/de.json
>  				"header": "GESTURES",
"Stärke für Beitrags-Titel"

2023-07-24 05:52 UTC, phriedrich commented on src/plugins/i18n/locales/de.json
> +  "Legal Info": "Rechtliche Infos",
Sounds good

2023-07-24 05:55 UTC, Felix-Staud commented on src/plugins/i18n/locales/de.json
> +  "Post": "Beitrag erstellen",
Agree

2023-07-24 05:55 UTC, phriedrich commented
I think I got all

2023-07-24 06:00 UTC, Felix-Staud commented
I think it looks good now, you have to resolve the merge conflicts though @phriedrich . _If you don’t know how to do that I can help you_

2023-07-24 06:15 UTC, phriedrich commented
I think I got it

2023-07-24 06:25 UTC, Felix-Staud approved these changes
@sgriff96 LGTM

2023-07-26 04:49 UTC, merged

2023-07-26 05:23 UTC, Felix-Staud commented
@phriedrich congrats on your first PR 🎉.

_danke für deine Unterstützung_